# Generated by Django 4.2.2 on 2023-06-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ooredoo',
        ),
        migrations.DeleteModel(
            name='Orange',
        ),
    ]
