# Generated by Django 4.2.2 on 2023-06-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_myuploadfile_date_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne_fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anumber', models.IntegerField(null=True)),
                ('Bnumber', models.IntegerField(null=True)),
                ('origine_trafic', models.CharField(max_length=255)),
                ('call_day', models.DateField()),
                ('call_time', models.DateField()),
                ('call_duration', models.IntegerField(null=True)),
                ('ALL', models.CharField(max_length=20)),
                ('Calltype', models.CharField(max_length=20)),
                ('callreference', models.IntegerField(null=True)),
                ('pulse', models.IntegerField(null=True)),
                ('node', models.CharField(max_length=255)),
                ('Intrunk', models.CharField(max_length=255)),
                ('Outtrunk', models.CharField(max_length=255)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.myuploadfile')),
            ],
        ),
    ]
