# Generated by Django 4.2.2 on 2023-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_ligne_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileuploaded', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='ALL',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='Calltype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='Intrunk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='Outtrunk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='call_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='call_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='node',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ligne_fichier',
            name='origine_trafic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
