# Generated by Django 4.2.2 on 2023-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_uploadfile_alter_ligne_fichier_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne_fichier',
            name='call_day',
            field=models.DateField(default='2023-06-22', null=True),
        ),
    ]
