# Generated by Django 4.2.2 on 2023-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_ligne_fichier_call_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pays', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=10)),
            ],
        ),
    ]
